# name: Build

# on:
#   push:
#     branches:
#       - main

# jobs:
#   sonarQubeScan1:
#     name: sonarQubeScan1
#     runs-on: ubuntu-latest
    
#     steps:
#       - uses: actions/checkout@v4
#         with:
#           fetch-depth: 0 
#       - name: SonarQube Scan 
#         uses: sonarsource/sonarqube-scan-action@master
#         env:
#           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
#           # SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
#         with:
#           # projectBaseDir: ./ 
#           args: >
#             - Dsonar.organiztion=sarikamahboob
#             - Dsonar.projectKey=expense_tracker
#             - Dsonar.sources=.

name: Build

on:
  push:
    branches:
      - main

jobs:
  sonarQubeScan1:
    name: sonarQubeScan
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
        with:
          projectBaseDir: ./ 
          args: >
            -Dsonar.organization=sarikamahboob
            -Dsonar.projectKey=expense_tracker
            -Dsonar.sources=.
            -Dsonar.language=js
